<div>
    <div class="b-radius padded-30 bg-grey cart-elements-wrapper">
        <ul class="list list--table borderless cart-details">
            <li class="list--table__head bg-white b-radius">
                <div>
                    <span>المنتج</span>
                </div>
                <div>
                    <span>
                    السعر
                    </span>
                    <span>
                    الكمية
                    </span>
                    <span class="text-left">
                    المجموع
                    </span>
                    <span class="delete-item"></span>
                </div>
            </li>
        
            @foreach ($cart->products as $cartProduct)
                <li class="cart-product-entry padded-10 bg-white b-radius mb-30">
                    <div class="hydrated col-md-12"><!---->
                        <div class="product-block product-block--inline">
                            <div class="product-block__thumb center">
                                <a class="d-flex" href="{{ route('store-customer.products.show', [$cart->store->slug, $cartProduct]) }}">
                                    <span class="avatar-wrapper avatar-wrapper--bordered avatar-wrapper--circular avatar-wrapper--small placeholder">
                                    <img class="loaded" alt="{{ $cartProduct->name }}" src="{{ $cartProduct->getFirstMedia('image')?->getUrl() }}">
                                    </span>
                                    <span>
                                    <h6 class="title title--small">
                                    {{ $cartProduct->name }}
                                    </h6>
                                    </span>
                                </a>
                            </div>
                            <div class="product-block__info">
                                <span class=" cart-item-price" data-title="السعر">
                                    {!! round($cartProduct->price, 2) !!} {{ session('current_currency', 'EGP') }}
                                </span>
                                <span data-title="الكمية">
                                    <div class="transtion transition-color duration-300 s-quantity-input hydrated" name="quantity"><!---->
                                        <div class="s-quantity-input-container">
                                            <button class="s-quantity-input-increase-button s-quantity-input-button" type="button" wire:click.stop="increaseItem('{{ $cartProduct->id}}')">
                                                <span><!-- Generated by IcoMoon.io -->
                                                    <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                                                    <title>add</title>
                                                    <path d="M26.667 14.667h-9.333v-9.333c0-0.736-0.597-1.333-1.333-1.333s-1.333 0.597-1.333 1.333v9.333h-9.333c-0.736 0-1.333 0.597-1.333 1.333s0.597 1.333 1.333 1.333h9.333v9.333c0 0.736 0.597 1.333 1.333 1.333s1.333-0.597 1.333-1.333v-9.333h9.333c0.736 0 1.333-0.597 1.333-1.333s-0.597-1.333-1.333-1.333z"></path>
                                                    </svg>
                                                </span>
                                            </button>
                                            <input class="s-quantity-input-input" max="{{ $cartProduct->max_quantity }}" name="quantity" min="1" value="{{ $cartProduct->pivot->quantity }}">
                                            <button class="s-quantity-input-decrease-button s-quantity-input-button" type="button" wire:click.stop="decreaseItem('{{ $cartProduct->id}}')">
                                                <span><!-- Generated by IcoMoon.io -->
                                                    <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                                                    <title>minus</title>
                                                    <path d="M26.667 14.667h-21.333c-0.736 0-1.333 0.597-1.333 1.333s0.597 1.333 1.333 1.333h21.333c0.736 0 1.333-0.597 1.333-1.333s-0.597-1.333-1.333-1.333z"></path>
                                                    </svg>
                                                </span>
                                            </button>
                                        </div>
                                    </div>
                                </span>
                                <span class="font-bold text-left cart-item-total" data-title="المجموع">
                                    {!! round($cartProduct->pivot->quantity * $cartProduct->price, 2) !!} {{ session('current_currency', 'EGP') }}
                                </span>
                                <span class="delete-entry">
                                    <button type="button" shape="icon" size="small" color="danger" class="btn--delete s-button-wrap hydrated" fill="solid" width="normal"><!---->
                                        <button type="button" shape="icon" class="btn--delete s-button-element s-button-icon s-button-solid s-button-small s-button-danger s-button-loader-center" wire:click.stop="deleteItem('{{ $cartProduct->id}}')">
                                            <span class="s-button-text">
                                                <i class="sicon-cancel"></i>
                                            </span>
                                        </button>
                                    </button>
                                </span>
                            </div>
                        </div>
                    </div>
                </li>
            @endforeach

            <li class="total padded-20 bg-white b-radius mb-30">
                <div class="wide no-p summary">
                    <div class="form form--coupon">
                        <div class="form-group">
                            <input placeholder="ادخل كود الخصم" class="form-control coupone-code__input" id="coupon-input" name="coupon" type="text" value="">
                            <span id="coupon-error"></span>
                            <button class="coupone-code__submit has-not-coupon s-button-element s-button-btn s-button-solid s-button-primary s-button-loader-center" loader-position="center" type="button">
                                <span class="s-button-text">
                                    <span class="coupon-text">إضافة</span>
                                    <i class="sicon-cancel icon"></i>
                                </span>
                            </button>
                        </div>
                    </div>
                    <div class="mt-0 mb-0">
                        <span>عدد الأصناف</span>
                        <span id="cart-items-count">{{ $cart->products()->sum('cart_product.quantity') }}</span>
                    </div>
                    <div class="sub-total">
                        <span>مجموع المنتجات</span>
                        <span id="cart-sub-total">{{ $cart->products()->get()->sum(function($product) {
                            return $product->pivot->quantity * $product->price;
                        })}} {{ session('current_currency', 'EGP') }}</span>
                    </div>
                    <div class="discount hidden">
                        <span>الخصم</span>
                        <span id="cart-total-discount">-
                        0 EGP</span>
                    </div>
                    <div class="total color-primary no-border">
                        <span>الإجمالي</span>
                        <span id="cart-final-total" data-cart-total="">
                            {{ $cart->products()->get()->sum(function($product) {
                                return $product->pivot->quantity * $product->price;
                            })}} {{ session('current_currency', 'EGP') }}
                        </span>
                    </div>
                </div>
            </li>

        </ul>
        <div class="cart-bottom-actions">
            <button class="btn--oval btn--md s-button-element s-button-btn s-button-solid s-button-wide s-button-primary s-button-loader-end cart-place-order" loader-position="end" type="button">
                <span class="s-button-text">
                    اتمام الطلب
                </span>
            </button>
        </div>
    </div>

    @once
        @push('scripts')
            <script>
                document.addEventListener('livewire:init', () => {
                    Livewire.on('update-cart-info', (event) => {
                        $(".s-cart-summary-count").text(event.count);
                        $(".s-cart-summary-total").text(event.total);
                    });

                    Livewire.on('update-cart-error', (event) => {
                        Swal.fire({
                            title: event.message,
                            text: event.message,
                            icon: "error"
                        });
                    });
                });

                $(".cart-place-order").on('click', function() {
                    Swal.fire({
                        title: "Are you sure?",
                        icon: "warning",
                        showCancelButton: true,
                        confirmButtonColor: "#3085d6",
                        cancelButtonColor: "#d33",
                        confirmButtonText: "Yes"
                    }).then((result) => {
                        if (result.isConfirmed) {
                            location.href = "{{ route('store-customer.order.processing', $this->cart->store) }}";
                            // Livewire.dispatch('placeOrder');
                        }
                    });
                });
            </script>
        @endpush
    @endonce
</div>
